### PR TITLE
Add rules

### PR DESCRIPTION
**Pull request by jfmengels**
Add the concept of Rules, and start looping over rules to get errors.

I still want to get the errors to automatically take the name of the rule (to remove duplication) but that can happen later.

### CODE REVIEW

**Comment by bcpeinhardt** [comment]
I think even though we don't see it this PR has a rule that only applies in functions visiting the expressions in constants and a rule that only applies in constants visiting the expressions in functions. I split the rules because I wanted the one for functions to have the extra context of a function name, but I don't think we'll always have that. Maybe the thing to do here is make function_name optional in RuleError? Not all RuleErrors will be produced from inside a function. What do you think?

Overall I really like the constructs though.

**Comment by bcpeinhardt** [comment]
We're also getting doubles of each lint I think. debug has six examples and twelve are printing to the terminal.

**Comment by bcpeinhardt** [comment]
Yeah, lets keep it how it is now but rename it like "location_identifier" or something so we can use it for const names and import statements etc etc. The we'll just have it be something in the description once we have proper locations.

Haha @giacomocavalieri (Jak in discord) is the author of a snapshot testing library for gleam called birdie, I'll defer to him as the expert on that so I don't have to set it up myself.

**Comment by giacomocavalieri** [comment]
Hello hello! I was planning to work on adding some tests this weekend but if you want to get to it earlier, please do! 💕
I think snapshot tests would be a perfect fit here but I might be biased 😆

**Comment by bcpeinhardt** [comment]
I agree snapshot tests will be fabulous so we don't have to constantly duplicate `RuleError`s for testing

**Comment by jfmengels** [comment]
I think snapshot tests are okay for this, but I like my approach of a dedicated test library better (though obviously that depends on some things that I have little knowledge about like the Gleam language and your snapshot library). I've explained some of that in https://github.com/jfmengels/elm-review/blob/master/documentation/design/test-module.md

My bias/feeling (from my experience) is that with snapshot tests incorrect results can easily go unnoticed, either when adding a new test or when making other changes that are expected. With tests you have to write yourself this is less likely to happen.

Here's an example of a test: https://github.com/jfmengels/elm-review-simplify/blob/main/tests/Simplify/BasicsTest.elm#L67-L82

Here tests have a title (which I often find missing in snapshot tests in other linters) which can explain some complex context ("should do X when Y but not Z"). Having both the title giving context, the input and the expected output in the same location makes it quite a bit easier. Note, if you think some details are copied over and over, you can extract them to variables. I decided to prefer not doing so, it makes the test easier to read without looking up the value of other things.

The test checks pretty much that all data is as expected, nothing (error message, details, location) is left unchecked. I think you'd get the same results with snapshots here.


The `under` field explains where we expect to see the squiggly lines. You could snapshot the location (start and end line/column) but if you don't check what that corresponds to, then you could target ` "abc` instead of `"abc"`, or target several lines (that's a lot of squiggly lines for the user, really not nice).

(If the value for "under" appears multilpe times, then the test framework forces you to use the `Review.Test.atExactly` function like below)
```elm
Review.Test.error
  { message = "Remove the use of `Debug` before shipping to production"
  , details = [ "Details about the error" ]
  , under = "Debug.log"
  }
  |> Review.Test.atExactly { start = { row = 5, column = 5 }, end = { row = 5, column = 14 } }
```

I have seen I think Biomejs do a snapshot of the error message shown to the user with the squiggly lines, which could also work to see the error message.

Another thing that the test framework does, is check a lot of things that improve the user experience that I don't think can be done by just snapshotting the linting results:
- Make sure that error message and details are not empty
- Make sure that the provided fix is correct by trying it out. i.e. it's not nonsensical, it does change the code, the result is still syntactically correct. Also, you need to provide the expected fix)
- for the dev: report when the input data is bad: duplicate file names, syntax errors in input code, etc.
- Test the rule in different conditions (something a bit advanced in `elm-review`, not sure mentioning too much)


Honestly, if you go with good snapshots, you'll get most of the way there, and it would be great already. I don't think that it's as good as it can be, and I see definite value in having output located with the input (I'm assuming the snapshots are saved in other files).

Ok, back to fixing the duplication errors, this was very off-topic, happy to discuss this again (but maybe in another GitHub issue :sweat_smile: )

**Comment by jfmengels** [comment]
@bcpeinhardt I uncovered the duplication, it's because I started using `do_visit_expressions` which used both an accumulator and `flat_map`, which led to duplicating the contents of `acc`.

I have also
- removed the duplicate constant panic function, it was reporting the same things as the other rule with the previous PR
  - I think they can later be joined into a single rule, and if we'd like, have different error messages based on where they are, based on the "context" of the node. But that's a future improvement.
- Renamed the rules to indicate to be in a negative form (https://package.elm-lang.org/packages/jfmengels/elm-review/latest/Review-Rule#a-good-rule-name)

Let me know if I went overboard with too many changes in this PR :eyes:

**Comment by bcpeinhardt** [comment]
Haha no worries, we can start being good about small PRs once we actually have a codebase.
Sweet, I'm going to merge this and then maybe investigate a test setup later if I have the time. Thank you!

**Comment by jfmengels** [comment]
My pleasure.

Feel free to go with a snapshot approach for now, especially while everything is very much in flux (but be sure to at least revisit the approach later! :sweat_smile: )

**Comment by giacomocavalieri** [comment]
@jfmengels thank you for taking the time to write such a good and detailed answer! I've only ever used snapshot tests in the gleam compiler so I totally trust you here, the tests you showed here look amazing! I'm convinced we'll want something like those for whinge as well

**Pull request merged**
